#!/bin/bash
# CDCS Master Context Aggregator
# Runs every hour to create a unified context snapshot

OUTPUT_DIR="/Users/sac/claude-desktop-context/cron/snapshots"
FINAL_OUTPUT="/Users/sac/claude-desktop-context/CONTEXT_SNAPSHOT.md"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Create comprehensive context file
cat > "$FINAL_OUTPUT" << EOF
# CDCS Context Snapshot
Generated: $TIMESTAMP
System: Claude Desktop Context System v2.0

This file provides a comprehensive view of the current CDCS state, automatically
generated by cron jobs for optimal context loading on startup.

================================================================================

EOF

# Add directory structure
echo "## System Structure Overview" >> "$FINAL_OUTPUT"
echo '```' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/structure_latest.txt" ]; then
    # Just the tree part, not the full file
    head -50 "$OUTPUT_DIR/structure_latest.txt" >> "$FINAL_OUTPUT"
    echo "... (truncated for context efficiency)" >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add key metrics summary
echo "## Key Performance Metrics" >> "$FINAL_OUTPUT"
echo '```yaml' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/performance_metrics.txt" ]; then
    grep -A20 "=== Context Efficiency Metrics ===" "$OUTPUT_DIR/performance_metrics.txt" | tail -n +2 | head -15 >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add memory activity summary
echo "## Memory System Status" >> "$FINAL_OUTPUT"
echo '```' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/memory_activity.txt" ]; then
    grep -A10 "=== Recent Session Activity ===" "$OUTPUT_DIR/memory_activity.txt" | tail -n +2 >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add pattern analytics summary
echo "## Active Patterns Summary" >> "$FINAL_OUTPUT"
echo '```' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/pattern_analytics.txt" ]; then
    grep -A20 "=== Pattern Inventory ===" "$OUTPUT_DIR/pattern_analytics.txt" | tail -n +2 >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add recent changes
echo "## Recent System Changes" >> "$FINAL_OUTPUT"
echo '```' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/changes.txt" ]; then
    grep -A20 "=== Files Changed Since Last Check ===" "$OUTPUT_DIR/changes.txt" | tail -n +2 | head -15 >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add entropy analysis highlights
echo "## Entropy Analysis Highlights" >> "$FINAL_OUTPUT"
echo '```' >> "$FINAL_OUTPUT"
if [ -f "$OUTPUT_DIR/entropy_analysis.txt" ]; then
    grep -A5 "=== Compression Recommendations ===" "$OUTPUT_DIR/entropy_analysis.txt" | tail -n +2 >> "$FINAL_OUTPUT"
fi
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add quick statistics
echo "## Quick Statistics" >> "$FINAL_OUTPUT"
echo '```yaml' >> "$FINAL_OUTPUT"
cat >> "$FINAL_OUTPUT" << EOF
cdcs_root: /Users/sac/claude-desktop-context
total_files: $(find /Users/sac/claude-desktop-context -type f | wc -l | xargs)
total_patterns: $(find /Users/sac/claude-desktop-context/patterns/catalog -name "*.yaml" 2>/dev/null | wc -l | xargs)
active_sessions: $(find /Users/sac/claude-desktop-context/memory/sessions -name "*.md" -mtime -1 2>/dev/null | wc -l | xargs)
discovered_capabilities: $(find /Users/sac/claude-desktop-context/emergent-capabilities/discovered -name "*.md" 2>/dev/null | wc -l | xargs)
pending_mutations: $(find /Users/sac/claude-desktop-context/evolution/mutations/pending -name "*.md" 2>/dev/null | wc -l | xargs)
system_size: $(du -sh /Users/sac/claude-desktop-context | cut -f1)
last_evolution: $(ls -t /Users/sac/claude-desktop-context/evolution/mutations/*/  2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "none")
EOF
echo '```' >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Add actionable items
echo "## Actionable Items" >> "$FINAL_OUTPUT"
echo "" >> "$FINAL_OUTPUT"

# Check for compression needs
comp_needed=$(find /Users/sac/claude-desktop-context/memory/sessions -name "*.md" -size +500k 2>/dev/null | wc -l)
if [ "$comp_needed" -gt 0 ]; then
    echo "- **Memory Compression Needed**: $comp_needed large session files detected" >> "$FINAL_OUTPUT"
fi

# Check for high-confidence patterns not in cache
high_patterns=$(find /Users/sac/claude-desktop-context/patterns/catalog -name "*.yaml" -exec grep -l "confidence: 0\.[89]" {} \; 2>/dev/null | wc -l)
if [ "$high_patterns" -gt 100 ]; then
    echo "- **Pattern Cache Overflow**: Consider increasing cache size (currently 100, have $high_patterns high-confidence patterns)" >> "$FINAL_OUTPUT"
fi

# Check for stale hypotheses
old_hyp=$(find /Users/sac/claude-desktop-context/emergent-capabilities/hypotheses -name "*.md" -mtime +7 2>/dev/null | wc -l)
if [ "$old_hyp" -gt 0 ]; then
    echo "- **Stale Hypotheses**: $old_hyp hypotheses older than 7 days need testing or removal" >> "$FINAL_OUTPUT"
fi

echo "" >> "$FINAL_OUTPUT"
echo "---" >> "$FINAL_OUTPUT"
echo "*Context snapshot complete. This file is regenerated hourly by cron jobs.*" >> "$FINAL_OUTPUT"

# Also create a compressed version for quick loading
gzip -c "$FINAL_OUTPUT" > "$OUTPUT_DIR/context_snapshot.md.gz"

# Log completion
echo "Context aggregation completed at $TIMESTAMP" >> "$OUTPUT_DIR/aggregator.log"